// app/components/constants.js
// Pure data constants — no React, no dependencies

var METRICS=[
  // Revenue & Growth
  {id:"revenue",label:"Revenue",unit:"$B",cat:"Revenue",fh:"revenue"},{id:"revGrowth",label:"Revenue Growth YoY",unit:"%",cat:"Revenue"},{id:"revPerShare",label:"Revenue Per Share",unit:"$",cat:"Revenue"},{id:"orgGrowth",label:"Organic Revenue Growth",unit:"%",cat:"Revenue"},{id:"arr",label:"Annual Recurring Revenue (ARR)",unit:"$M",cat:"Revenue"},{id:"nrr",label:"Net Revenue Retention",unit:"%",cat:"Revenue"},{id:"mrr",label:"Monthly Recurring Revenue (MRR)",unit:"$M",cat:"Revenue"},{id:"arpu",label:"ARPU",unit:"$",cat:"Revenue"},{id:"bookings",label:"Bookings / Backlog",unit:"$B",cat:"Revenue"},
  // Earnings & Profitability
  {id:"eps",label:"EPS",unit:"$",cat:"Earnings",fh:"earnings"},{id:"epsGrowth",label:"EPS Growth YoY",unit:"%",cat:"Earnings"},{id:"ebitda",label:"EBITDA",unit:"$B",cat:"Earnings"},{id:"ebitdaPerShare",label:"EBITDA / Share",unit:"$",cat:"Earnings"},{id:"ebitdaMargin",label:"EBITDA Margin",unit:"%",cat:"Earnings"},{id:"netIncome",label:"Net Income",unit:"$B",cat:"Earnings"},{id:"adjEPS",label:"Adjusted EPS",unit:"$",cat:"Earnings"},
  // Margins
  {id:"grossMargin",label:"Gross Margin",unit:"%",cat:"Margins"},{id:"opMargin",label:"Operating Margin",unit:"%",cat:"Margins"},{id:"netMargin",label:"Net Margin",unit:"%",cat:"Margins"},{id:"fcfMargin",label:"FCF Margin",unit:"%",cat:"Margins"},{id:"rndMargin",label:"R&D / Revenue",unit:"%",cat:"Margins"},{id:"sgaMargin",label:"SG&A / Revenue",unit:"%",cat:"Margins"},
  // Cash Flow
  {id:"fcf",label:"Free Cash Flow",unit:"$B",cat:"Cash Flow"},{id:"fcfPerShare",label:"FCF / Share",unit:"$",cat:"Cash Flow"},{id:"ocf",label:"Operating Cash Flow",unit:"$B",cat:"Cash Flow"},{id:"capex",label:"Capital Expenditure",unit:"$B",cat:"Cash Flow"},{id:"fcfConversion",label:"FCF Conversion",unit:"%",cat:"Cash Flow"},{id:"cashFromOps",label:"Cash from Operations",unit:"$B",cat:"Cash Flow"},
  // Returns
  {id:"roe",label:"ROE",unit:"%",cat:"Returns"},{id:"roa",label:"ROA",unit:"%",cat:"Returns"},{id:"roic",label:"ROIC",unit:"%",cat:"Returns"},{id:"roce",label:"ROCE",unit:"%",cat:"Returns"},{id:"rotce",label:"ROTCE",unit:"%",cat:"Returns"},
  // Valuation
  {id:"pe",label:"P/E Ratio",unit:"x",cat:"Valuation"},{id:"pb",label:"P/B Ratio",unit:"x",cat:"Valuation"},{id:"ps",label:"P/S Ratio",unit:"x",cat:"Valuation"},{id:"evEbitda",label:"EV/EBITDA",unit:"x",cat:"Valuation"},{id:"evRevenue",label:"EV/Revenue",unit:"x",cat:"Valuation"},{id:"evFcf",label:"EV/FCF",unit:"x",cat:"Valuation"},{id:"bvps",label:"Book Value / Share",unit:"$",cat:"Valuation"},{id:"peg",label:"PEG Ratio",unit:"x",cat:"Valuation"},
  // Health & Balance Sheet
  {id:"currentRatio",label:"Current Ratio",unit:"x",cat:"Health"},{id:"debtEquity",label:"Debt / Equity",unit:"x",cat:"Health"},{id:"netDebtEbitda",label:"Net Debt / EBITDA",unit:"x",cat:"Health"},{id:"interestCoverage",label:"Interest Coverage",unit:"x",cat:"Health"},{id:"cashOnHand",label:"Cash on Hand",unit:"$B",cat:"Health"},{id:"totalDebt",label:"Total Debt",unit:"$B",cat:"Health"},{id:"quickRatio",label:"Quick Ratio",unit:"x",cat:"Health"},
  // Income & Dividends
  {id:"divYield",label:"Dividend Yield",unit:"%",cat:"Income"},{id:"divPerShare",label:"Dividend / Share",unit:"$",cat:"Income"},{id:"payoutRatio",label:"Payout Ratio",unit:"%",cat:"Income"},{id:"divGrowth",label:"Dividend Growth YoY",unit:"%",cat:"Income"},{id:"buybackYield",label:"Buyback Yield",unit:"%",cat:"Income"},{id:"shareholderYield",label:"Shareholder Yield",unit:"%",cat:"Income"},
  // SaaS / Tech
  {id:"grossRetention",label:"Gross Retention Rate",unit:"%",cat:"SaaS"},{id:"netRetention",label:"Net Dollar Retention",unit:"%",cat:"SaaS"},{id:"cac",label:"Customer Acquisition Cost",unit:"$",cat:"SaaS"},{id:"ltv",label:"Customer LTV",unit:"$",cat:"SaaS"},{id:"ltvCac",label:"LTV/CAC Ratio",unit:"x",cat:"SaaS"},{id:"churnRate",label:"Churn Rate",unit:"%",cat:"SaaS"},{id:"ruleOf40",label:"Rule of 40",unit:"%",cat:"SaaS"},{id:"magicNumber",label:"Magic Number",unit:"x",cat:"SaaS"},
  // Users & Engagement
  {id:"mau",label:"Monthly Active Users (MAU)",unit:"M",cat:"Users"},{id:"dau",label:"Daily Active Users (DAU)",unit:"M",cat:"Users"},{id:"subscribers",label:"Subscribers",unit:"M",cat:"Users"},{id:"customers",label:"Customers",unit:"k",cat:"Users"},{id:"gmv",label:"GMV (Gross Merch Value)",unit:"$B",cat:"Users"},{id:"takeRate",label:"Take Rate",unit:"%",cat:"Users"},
  // Segment-specific
  {id:"sameStoreSales",label:"Same-Store Sales Growth",unit:"%",cat:"Retail"},{id:"storeCount",label:"Store Count",unit:"#",cat:"Retail"},{id:"revPerSqFt",label:"Revenue / Sq Ft",unit:"$",cat:"Retail"},{id:"occupancy",label:"Occupancy Rate",unit:"%",cat:"REIT"},{id:"ffo",label:"FFO / Share",unit:"$",cat:"REIT"},{id:"nim",label:"Net Interest Margin",unit:"%",cat:"Banking"},{id:"cet1",label:"CET1 Ratio",unit:"%",cat:"Banking"},{id:"combinedRatio",label:"Combined Ratio",unit:"%",cat:"Insurance"},{id:"ber",label:"Break-Even Ratio",unit:"%",cat:"Insurance"}
];
var METRIC_MAP={};METRICS.forEach(function(m){METRIC_MAP[m.id]=m});
var INVEST_STYLES=[
  {id:"quality",label:"Quality Compounder",icon:"shield",color:"#22C55E",
    desc:"Wide moat, durable earnings, compound forever. Think Visa, Costco, MSFT.",
    kpis:["roic","grossMargin","opMargin","fcfPerShare","roe"],
    thesisPrompt:"What makes this a durable competitive advantage? How does the moat compound over time?",
    moatPrompt:"What protects this business from competition for the next 10+ years?",
    riskPrompt:"What could erode the moat? Disruption, complacency, regulatory change?",
    sellPrompt:"At what valuation does even a great compounder become a sell?"},
  {id:"growth",label:"High Growth",icon:"trending",color:"#3B82F6",
    desc:"Rapid revenue growth, path to profitability matters. Think early CrowdStrike, Shopify.",
    kpis:["revGrowth","grossMargin","opMargin","revPerShare","epsGrowth"],
    thesisPrompt:"What's the total addressable market? Why will this company win it?",
    moatPrompt:"What creates winner-take-most dynamics? Network effects, switching costs, data moats?",
    riskPrompt:"Can growth sustain? Competition, customer concentration, burn rate?",
    sellPrompt:"What growth deceleration would signal the thesis is broken?"},
  {id:"prerev",label:"Pre-Revenue / Speculative",icon:"flask",color:"#EC4899",
    desc:"No financials yet — catalysts and optionality matter. Think biotech, early-stage tech.",
    kpis:["currentRatio","debtEquity"],
    thesisPrompt:"What's the specific catalyst? FDA approval, product launch, key partnership?",
    moatPrompt:"What IP, regulatory, or first-mover advantage exists? What's the optionality?",
    riskPrompt:"Cash runway? Binary risk events? Dilution risk? What kills this if it fails?",
    sellPrompt:"What catalyst failure or timeline miss would make you exit?"},
  {id:"dividend",label:"Dividend / Income",icon:"dollar",color:"#F59E0B",
    desc:"Stable cash flows, growing dividends. Think JNJ, Realty Income, Coca-Cola.",
    kpis:["divYield","fcfPerShare","debtEquity","roe","opMargin"],
    thesisPrompt:"Why is this dividend safe and growing? What drives the underlying cash flow?",
    moatPrompt:"What ensures pricing power and demand stability through economic cycles?",
    riskPrompt:"Payout ratio sustainability? Interest rate sensitivity? Earnings cyclicality?",
    sellPrompt:"What dividend cut, yield threshold, or growth stall would trigger a sell?"},
  {id:"garp",label:"GARP",icon:"bar",color:"#8B5CF6",
    desc:"Growth at a reasonable price. PEG matters. Think FICO, Danaher, Mastercard.",
    kpis:["revGrowth","epsGrowth","pe","grossMargin","roic"],
    thesisPrompt:"Is this growth fairly priced? What's the PEG ratio telling you?",
    moatPrompt:"What competitive advantage sustains above-market growth without excessive risk?",
    riskPrompt:"Multiple compression risk? Can growth justify the premium? Cyclical exposure?",
    sellPrompt:"At what P/E or PEG does the risk/reward no longer favor holding?"},
  {id:"value",label:"Deep Value",icon:"search",color:"#6366F1",
    desc:"Trading below intrinsic value. Margin of safety is everything. Think Buffett's cigar butts.",
    kpis:["pb","pe","currentRatio","debtEquity","bvps"],
    thesisPrompt:"What's the intrinsic value? Why is the market mispricing this asset?",
    moatPrompt:"Is there hidden asset value, franchise value, or earnings power the market ignores?",
    riskPrompt:"Value trap risk? Is it cheap for a reason? Management quality? Balance sheet?",
    sellPrompt:"What's your intrinsic value estimate? At what price do you sell?"},
  {id:"turnaround",label:"Turnaround",icon:"gear",color:"#EF4444",
    desc:"Broken but fixable. Catalyst for recovery needed. Think post-crisis plays.",
    kpis:["debtEquity","opMargin","currentRatio","revGrowth","fcfPerShare"],
    thesisPrompt:"What's broken and what's the specific fix? New management, restructuring, spinoff?",
    moatPrompt:"What underlying franchise value survives the current problems?",
    riskPrompt:"Can the company survive long enough? Liquidity risk? Execution risk on the turnaround plan?",
    sellPrompt:"What timeline for recovery? What would prove the turnaround thesis is dead?"}
];
var STYLE_MAP={};INVEST_STYLES.forEach(function(s){STYLE_MAP[s.id]=s});
var INVESTOR_PROFILES=[
  {id:"terry",name:"Terry Smith",fund:"Fundsmith",
   tagline:"Buy wonderful companies at fair prices. Never sell.",
   focus:"Financial quality: ROIC, gross margin, FCF conversion. If the numbers aren't exceptional, the moat isn't real.",
   color:"#22C55E",icon:"shield",
   dashDefault:"fundamentals",
   fundCols:["grossMargin","opMargin","roic","fcfYield","revGrowth"],
   listCols:{conviction:true,kpis:true},
   morningPriority:["kpi_streak","stale_thesis","above_iv"],
   dossierFirst:"numbers",
   quote:"We do not invest in businesses we do not understand or which we believe have poor prospects.",
   thesisPrompt:"Why does this business earn high returns on capital, and what structural reason prevents those returns from being competed away?",
   moatPrompt:"Does this business have genuine pricing power — could it raise prices without losing customers?",
   riskPrompt:"What could cause returns on capital to structurally decline? Think capital intensity creep, disruption, or management misallocation.",
   sellPrompt:"At what price or ROCE level does the quality no longer justify holding?",
   newWidget:"quality_scorecard"},
  {id:"sleep",name:"Nick Sleep",fund:"Nomad Investment Partnership",
   tagline:"Scale economies shared. Find the businesses that get better for customers as they get bigger.",
   focus:"Unit economics, reinvestment rate, customer obsession. The financial metrics are a lagging indicator — the flywheel is what matters.",
   color:"#3B82F6",icon:"trending",
   dashDefault:"list",
   fundCols:["revGrowth","grossMargin","fcfYield","revPerShare"],
   listCols:{conviction:true,kpis:false,mastery:true},
   morningPriority:["stale_thesis","anniversary","earnings_note_missing"],
   dossierFirst:"story",
   quote:"The best investments I have made have been where I could see ten years ahead.",
   thesisPrompt:"Describe the flywheel in one paragraph: how does growth make this business better for customers, which drives more growth? If you cannot draw the loop clearly, the thesis is not ready.",
   moatPrompt:"Is there a self-reinforcing loop here — growth → better product → more growth? How hard is it to break?",
   riskPrompt:"What could stop the flywheel? A better-priced competitor, management shifting to margin extraction, or market saturation?",
   sellPrompt:"Has the company stopped reinvesting at high rates, or started optimising for short-term profit over long-term customer value?",
   newWidget:"reinvestment_widget"},
  {id:"munger",name:"Charlie Munger",fund:"Berkshire Hathaway",
   tagline:"All I want to know is where I am going to die, so I will never go there.",
   focus:"Moat first. Business model classification. Circle of competence. Inversion. The financials confirm — they don't decide.",
   color:"#F59E0B",icon:"castle",
   dashDefault:"ledger",
   fundCols:["grossMargin","roic","opMargin","netDebtEbitda"],
   listCols:{conviction:true,mastery:true,kpis:true},
   morningPriority:["conv_size","stale_thesis","kpi_streak"],
   dossierFirst:"moat",
   quote:"It is remarkable how much long-term advantage we have gotten by trying to be consistently not stupid.",
   thesisPrompt:"Invert first: what are the three ways this business fails? Now build the case against each failure mode. Only after inversion does the bull case matter.",
   moatPrompt:"Which moat type applies — brand, switching costs, network effects, cost advantage, or regulatory? How durable against a well-funded competitor?",
   riskPrompt:"What is outside your circle of competence here? What would a well-informed bear argue — and can you actually refute it?",
   sellPrompt:"Has the moat structurally eroded — not just cyclically weakened? Has the business moved outside your circle of competence?",
   newWidget:"checklist_widget"},
  {id:"lynch",name:"Peter Lynch",fund:"Magellan Fund",
   tagline:"Know what you own and know why you own it.",
   focus:"Can you explain the business simply? Growth relative to price. Everyday observation. The best stock is one you understand deeply.",
   color:"#8B5CF6",icon:"search",
   dashDefault:"list",
   fundCols:["revGrowth","epsGrowth","pe","grossMargin"],
   listCols:{conviction:true,kpis:true},
   morningPriority:["stale_thesis","kpi_streak","earnings_note_missing"],
   dossierFirst:"story",
   quote:"Behind every stock is a company. Find out what it is doing.",
   thesisPrompt:"The two-minute pitch: explain this business in two sentences a 10-year-old could understand. Then: what Lynch category is it, what is the PEG, and at what PEG or story change would you sell?",
   moatPrompt:"Is this company a clear leader in a niche it owns, or competing for share in a crowded market?",
   riskPrompt:"Is management diversifying into businesses it doesn't understand? Is the growth story still intact or quietly changing?",
   sellPrompt:"Has the stock outgrown its fundamentals — PEG above 2? Has the original story changed materially?",
   newWidget:"lynch_widget"},
  {id:"buffett",name:"Warren Buffett",fund:"Berkshire Hathaway",
   tagline:"Price is what you pay. Value is what you get.",
   focus:"Intrinsic value, margin of safety, economic moats, management quality. Only invest when the price makes sense relative to business value.",
   color:"#EF4444",icon:"dollar",
   dashDefault:"list",
   fundCols:["grossMargin","roic","roe","pe","fcfYield"],
   listCols:{conviction:true,kpis:true,mastery:true},
   morningPriority:["above_iv","conv_size","kpi_streak"],
   dossierFirst:"ledger",
   quote:"Our favourite holding period is forever.",
   thesisPrompt:"What is your intrinsic value estimate and what margin of safety does today's price offer? Would you hold this if the market closed for 10 years?",
   moatPrompt:"Will this economic moat still be intact in 20 years? What would it cost a competitor to replicate it from scratch?",
   riskPrompt:"Is management allocating capital rationally — avoiding empire building, buying back stock sensibly, being honest in their communications?",
   sellPrompt:"Has intrinsic value changed materially, or has price simply exceeded value? Is management doing something that breaks the original thesis?",
   newWidget:"iv_widget"},
  {id:"akre",name:"Chuck Akre",fund:"Akre Capital Management",
   tagline:"Three legs: extraordinary business, exceptional management, reinvestment opportunity.",
   focus:"Compounding machines. Return on equity, reinvestment rate, and management quality. Find businesses that can compound at high rates for decades and do nothing.",
   color:"#F97316",icon:"trending",
   dashDefault:"fundamentals",
   fundCols:["roe","roic","revGrowth","fcfYield","grossMargin"],
   listCols:{conviction:true,kpis:true,mastery:true},
   morningPriority:["stale_thesis","kpi_streak","anniversary"],
   dossierFirst:"story",
   quote:"The compounding of money over long periods of time is not limited by markets, economies, or politics. It is limited only by the quality of the businesses in which we invest.",
   thesisPrompt:"Score each leg: Leg 1 — Is ROE above 15% and why is it sustainable? Leg 2 — How does management define success, and do their actions match? Leg 3 — Where does excess cash go, and at what return rate for how many years?",
   moatPrompt:"What gives this business the ability to reinvest at high rates for years or decades — not just earn high returns today?",
   riskPrompt:"Which leg is weakest — business quality, management, or reinvestment runway? What would cause one leg to collapse?",
   sellPrompt:"Has ROE structurally declined, management quality deteriorated, or the reinvestment opportunity shrunk? Or has price simply exceeded compounding potential?",
   newWidget:"akre_widget"},
  {id:"custom",name:"Custom",fund:"",
   tagline:"Your own framework.",
   focus:"No preset. Configure the dashboard exactly as you like.",
   color:"#6B7280",icon:"gear",
   dashDefault:"fundamentals",
   fundCols:["revGrowth","grossMargin","opMargin","roic","netDebtEbitda"],
   listCols:{conviction:true,kpis:true},
   morningPriority:[],
   dossierFirst:"story",
   quote:"",
   newWidget:null}
];
var PROFILE_MAP={};INVESTOR_PROFILES.forEach(function(p){PROFILE_MAP[p.id]=p});
var SUPERINVESTORS=[
  {id:"berkshire",name:"Warren Buffett",fund:"Berkshire Hathaway",style:"Quality Value",desc:"Wonderful companies at fair prices. Concentrated, low turnover, moat-focused.",
    holdings:["AAPL","BAC","AXP","KO","CVX","OXY","MCO","KHC","CB","DVA","ALLY","VRSN","NU","AMZN","LLY"],
    traits:{quality:0.9,value:0.7,growth:0.2,income:0.5,concentration:0.8,turnover:0.1}},
  {id:"klarman",name:"Seth Klarman",fund:"Baupost Group",style:"Deep Value",desc:"Margin of safety obsessed. Contrarian, patient, often holds cash.",
    holdings:["LBTYA","LBTYK","QRTEA","FOXA","GOOGL","INTC","EBAY","WBD","PYPL","META","PARA","CRH","BEPC"],
    traits:{quality:0.4,value:0.95,growth:0.2,income:0.2,concentration:0.5,turnover:0.3}},
  {id:"ackman",name:"Bill Ackman",fund:"Pershing Square",style:"Activist Quality",desc:"Concentrated bets on high-quality businesses. Activist approach, pushes for value creation.",
    holdings:["GOOG","CMG","HLT","QSR","HHH","CP","LOW","NKE","UBER"],
    traits:{quality:0.8,value:0.5,growth:0.5,income:0.2,concentration:0.95,turnover:0.3}},
  {id:"smith",name:"Terry Smith",fund:"Fundsmith",style:"Quality Compounder",desc:"Buy good companies, don't overpay, do nothing. Ultra-low turnover, high ROIC focus.",
    holdings:["META","MSFT","NOVO-B","L'OREAL","IDEXX","VISA","ESTC","AMZN","MASI","WAT","POOL","FICO","PAYC","VEEV"],
    traits:{quality:0.95,value:0.3,growth:0.5,income:0.3,concentration:0.4,turnover:0.05}},
  {id:"hohn",name:"Chris Hohn",fund:"TCI Fund",style:"Activist FCF",desc:"Concentrated on free cash flow machines. Activist shareholder, pushes capital returns.",
    holdings:["GE","V","MSFT","MCO","SPGI","MA","GOOG","CNI","CSGP"],
    traits:{quality:0.85,value:0.4,growth:0.4,income:0.3,concentration:0.8,turnover:0.15}},
  {id:"lynch",name:"Peter Lynch",fund:"Magellan Fund",style:"Growth at Reasonable Price",desc:"Know what you own. Everyday observation, PEG ratio, growth with margin of safety.",
    holdings:["COST","HD","SBUX","NKE","TJX","WMT","MCD","PG","UNH","ABBV","JNJ","PEP","AMGN","TMO"],
    traits:{quality:0.6,value:0.5,growth:0.7,income:0.4,concentration:0.2,turnover:0.4}},
  {id:"greenblatt",name:"Joel Greenblatt",fund:"Gotham Asset Mgmt",style:"Magic Formula",desc:"High ROIC + high earnings yield. Systematic, quantitative approach to value.",
    holdings:["GOOG","META","MSFT","AAPL","AMZN","BRK-B","UNH","JNJ","PG","V","MA","HD","COST"],
    traits:{quality:0.6,value:0.8,growth:0.4,income:0.2,concentration:0.3,turnover:0.5}},
  {id:"einhorn",name:"David Einhorn",fund:"Greenlight Capital",style:"Value + Shorts",desc:"Classic value investor who also shorts overvalued stocks. Contrarian, forensic accounting focus.",
    holdings:["GPRE","TECK","GTN","ODP","CNX","GEN","JACK","CC","BHF","PRDO"],
    traits:{quality:0.3,value:0.9,growth:0.2,income:0.3,concentration:0.6,turnover:0.4}},
  {id:"marks",name:"Howard Marks",fund:"Oaktree Capital",style:"Distressed/Contrarian",desc:"Second-level thinker. Buys when others panic. Focused on risk control and cycles.",
    holdings:["OC","TEL","WMB","BKNG","LYB","NRG","PVH","CZR","HCA","DAL"],
    traits:{quality:0.4,value:0.85,growth:0.2,income:0.4,concentration:0.4,turnover:0.3}},
  {id:"kantesaria",name:"Dev Kantesaria",fund:"Valley Forge Capital",style:"Quality Compounder",desc:"15%+ compounders with minimal risk of permanent loss. Ultra-concentrated, high conviction.",
    holdings:["FICO","SPGI","MA","MCO","V","INTU","ROP","GOOG","MSFT"],
    traits:{quality:0.95,value:0.3,growth:0.5,income:0.1,concentration:0.9,turnover:0.05}},
  {id:"pabrai",name:"Mohnish Pabrai",fund:"Pabrai Investment Funds",style:"Cloner Value",desc:"Shamelessly clones the best ideas. Concentrated, high-conviction, Munger-inspired.",
    holdings:["COAL","TRMD","AMPS","JSPR","BATT","SATS","EXPE","TROW"],
    traits:{quality:0.5,value:0.8,growth:0.4,income:0.2,concentration:0.9,turnover:0.3}},
  {id:"burry",name:"Michael Burry",fund:"Scion Asset Mgmt",style:"Deep Value Contrarian",desc:"The Big Short. Extreme contrarian, forensic research, often against consensus.",
    holdings:["BABA","JD","GOOG","BKNG","ORLY","HCA","STLA","REAL"],
    traits:{quality:0.3,value:0.9,growth:0.3,income:0.1,concentration:0.7,turnover:0.7}},
  {id:"ainslie",name:"Lee Ainslie",fund:"Maverick Capital",style:"Long/Short Quality Growth",desc:"Growth-oriented with hedging. Deep fundamental research, sector-focused.",
    holdings:["MSFT","AMZN","META","GOOG","NVDA","CRM","SNOW","UBER","DASH","ABNB","COIN","DDOG"],
    traits:{quality:0.6,value:0.2,growth:0.9,income:0.0,concentration:0.4,turnover:0.5}},
  {id:"gayner",name:"Tom Gayner",fund:"Markel",style:"Patient Quality",desc:"Insurance-funded long-term equity portfolio. Patient, quality-focused, Buffett-inspired.",
    holdings:["BRK-B","GOOG","MSFT","DIS","BAM","AMZN","V","MA","HD","CME","WMT","KKR"],
    traits:{quality:0.8,value:0.5,growth:0.4,income:0.3,concentration:0.3,turnover:0.1}},
  {id:"akre",name:"Chuck Akre",fund:"Akre Capital Management",style:"Compounding Machines",desc:"Three-legged stool: extraordinary business, exceptional management, reinvestment opportunity. Buy and hold forever.",
    holdings:["MA","BN","KKR","V","MCO","FICO","CPRT","ORLY","MSCI","SPGI","CSGP","CCCS"],
    traits:{quality:0.95,value:0.4,growth:0.7,income:0.05,concentration:0.6,turnover:0.03}}
];
var MSTAR_RATINGS=["Wide","Narrow","None","Not Rated"];
var KNOWN_MONTHLY=["O","MAIN","STAG","AGNC","SLG","GOOD","LTC","SPHD","JEPI","JEPQ","QYLD","RYLD","DIVO","EPR","LAND","PSEC","GAIN"];
var DARK={bg:"#0F0F14",side:"#0A0A0E",card:"#16171E",bdr:"#22232E",bdr2:"#2E2F3C",txt:"#F0F0F4",mid:"#9496A1",dim:"#4A4B58",blue:"#F0F0F4",grn:"#86EFAC",red:"#FCA5A5",amb:"#9496A1",acc:"#7C6FE8",prim:"#7C6FE8",primTxt:"#ffffff"};
var LIGHT={bg:"#ECEEF4",side:"#1E2A3A",card:"#FFFFFF",bdr:"rgba(0,0,0,0.09)",bdr2:"rgba(0,0,0,0.16)",txt:"#0D1117",mid:"#4A5568",dim:"#8896A8",blue:"#2563eb",grn:"#059669",red:"#DC2626",amb:"#D97706",acc:"#2563eb",prim:"#2563eb",primTxt:"#ffffff",sideTxt:"#E8ECF5",sideMid:"rgba(232,236,245,0.65)",sideDim:"rgba(232,236,245,0.40)"};
var FOREST={bg:"#f7f7f5",side:"#1a4a00",card:"#ffffff",bdr:"#e2e8df",bdr2:"#c8d6c0",txt:"#1f2f1a",mid:"#4a6040",dim:"#8aaa80",blue:"#1cb0f6",grn:"#58cc02",red:"#ff4b4b",amb:"#ffc800",acc:"#58cc02",prim:"#58cc02",primTxt:"#ffffff",purple:"#ce82ff"};
var PURPLE={bg:"#0d0b14",side:"#090711",card:"#17132a",bdr:"rgba(167,139,250,0.12)",bdr2:"rgba(167,139,250,0.22)",txt:"#f0ecff",mid:"#b8aee0",dim:"#7065a0",blue:"#818cf8",grn:"#34d399",red:"#f87171",amb:"#fbbf24",acc:"#a78bfa",prim:"#a78bfa",primTxt:"#ffffff",glow:"rgba(167,139,250,0.15)"};
var BLOOMBERG={bg:"#000000",side:"#000000",card:"#0d0d0d",bdr:"#222222",bdr2:"#333333",txt:"#ffffff",mid:"#cccccc",dim:"#777777",blue:"#00c8d4",grn:"#00cc44",red:"#ff3333",amb:"#F39F41",acc:"#F39F41",prim:"#F39F41",primTxt:"#000000",sel:"#ffff00",selTxt:"#000000"};
var PAYPAL={bg:"#f0f4f8",side:"#0a2463",card:"#ffffff",bdr:"#cdd9e8",bdr2:"#aec0d4",txt:"#0d1b2a",mid:"#3d5a80",dim:"#7a94ae",blue:"#1a56db",grn:"#057a55",red:"#c81e1e",amb:"#d97706",acc:"#1a56db",prim:"#1a56db",primTxt:"#ffffff"};
var THESIS_DARK={bg:"#0F0F16",side:"#09090D",card:"#15151E",bdr:"rgba(255,255,255,0.06)",bdr2:"rgba(255,255,255,0.12)",txt:"#F2F2F6",mid:"rgba(242,242,246,0.60)",dim:"rgba(242,242,246,0.35)",blue:"#F2F2F6",grn:"#86EFAC",red:"#FCA5A5",amb:"rgba(242,242,246,0.45)",acc:"#7C6FE8",prim:"#7C6FE8",primTxt:"#ffffff"};
var THESIS_LIGHT={bg:"#ECEEF4",side:"#0F1A35",card:"#FFFFFF",bdr:"rgba(0,0,0,0.09)",bdr2:"rgba(0,0,0,0.16)",txt:"#0D1117",mid:"#4A5568",dim:"#8896A8",blue:"#2563eb",grn:"#059669",red:"#DC2626",amb:"#D97706",acc:"#6B4CE6",prim:"#6B4CE6",primTxt:"#ffffff",sideTxt:"#E8ECF5",sideMid:"rgba(232,236,245,0.65)",sideDim:"rgba(232,236,245,0.40)"};
var THEMES={thesis_dark:THESIS_DARK,thesis_light:THESIS_LIGHT,dark:DARK,light:LIGHT,forest:FOREST,purple:PURPLE,paypal:PAYPAL,bloomberg:BLOOMBERG};
var FOLDERS=[{id:"why-i-own",label:"Why I Own It",icon:"lightbulb"},{id:"my-writeups",label:"Investment Memos",icon:"edit"},{id:"deep-dives",label:"Research Clips",icon:"link"},{id:"reports",label:"IR Library",icon:"bar"},{id:"notes",label:"Quick Notes",icon:"file"}];
var SAMPLE=[{id:1,ticker:"NVDA",name:"NVIDIA Corporation",sector:"Semiconductors",domain:"nvidia.com",irUrl:"https://investor.nvidia.com",earningsDate:"2026-02-26",earningsTime:"AMC",lastChecked:null,notes:"",sourceUrl:"https://investor.nvidia.com",sourceLabel:"Q4 FY26",earningSummary:"Data Center revenue surged 93% YoY to $39.2B.",description:"NVIDIA designs and sells graphics processing units and system-on-chip units. The company's GPUs are the dominant platform for AI training and inference, powering data centers for hyperscalers, enterprises, and sovereign AI initiatives worldwide.",ceo:"Jensen Huang",employees:29600,country:"US",exchange:"NASDAQ",ipoDate:"1999-01-22",mktCap:3400000000000,thesisNote:"AI capex cycle still early innings.\n\n## MOAT\nNVIDIA owns the CUDA ecosystem — switching costs are massive. Every ML framework, every training pipeline, every inference stack is optimized for NVIDIA GPUs. This is a platform moat, not just a hardware moat.\n\n## RISKS\nCustom silicon (Google TPU, Amazon Trainium, AMD MI300) could erode share. Concentration in hyperscaler capex — if AI spending pauses, revenue craters.\n\n## SELL CRITERIA\nData Center growth below 30% YoY for 2 consecutive quarters. Gross margins below 65% sustained. Major customer (MSFT/GOOG/AMZN) publicly shifting >50% of AI training to non-NVIDIA silicon.",investStyle:"growth",position:{shares:50,avgCost:128.5},conviction:9,convictionHistory:[{date:"2025-06-01",rating:8,note:"Strong but expensive"},{date:"2025-11-20",rating:9,note:"Data center demand insatiable"},{date:"2026-01-15",rating:9,note:"AI capex still accelerating"}],status:"portfolio",docs:[{id:1,title:"Core Thesis: AI Infrastructure",folder:"why-i-own",content:"NVIDIA is the picks-and-shovels play on AI. Data center GPU demand is insatiable.",updatedAt:"2026-01-15T10:00:00Z"}],earningsHistory:[{quarter:"Q3 2025",summary:"Revenue $35.1B (+94% YoY). Data Center $30.8B. Gross margin 74.6%.",results:[{kpi_name:"Data Center Revenue",actual_value:30.8,status:"met",excerpt:"Data Center $30.8B"},{kpi_name:"Gross Margin",actual_value:74.6,status:"met",excerpt:"GAAP GM 74.6%"}],sourceUrl:"https://investor.nvidia.com",sourceLabel:"NVIDIA Press Release",checkedAt:"2025-11-20T18:00:00Z"},{quarter:"Q2 2025",summary:"Revenue $30.0B (+122% YoY). Data Center $26.3B. Gross margin 75.1%.",results:[{kpi_name:"Data Center Revenue",actual_value:26.3,status:"met",excerpt:"Data Center $26.3B"},{kpi_name:"Gross Margin",actual_value:75.1,status:"met",excerpt:"GAAP GM 75.1%"}],sourceUrl:"https://investor.nvidia.com",sourceLabel:"NVIDIA Press Release",checkedAt:"2025-08-28T18:00:00Z"}],kpis:[{id:1,name:"Data Center Revenue",target:"≥35B",rule:"gte",value:35,unit:"B",period:"Q4 FY26",notes:"",lastResult:{actual:39.2,status:"met",excerpt:"Data Center revenue was $39.2B."}},{id:2,name:"Gross Margin",target:"≥73%",rule:"gte",value:73,unit:"%",period:"Q4 FY26",notes:"GAAP",lastResult:{actual:73.5,status:"met",excerpt:"GAAP gross margin was 73.5%."}}]},{id:2,ticker:"CRWD",name:"CrowdStrike",sector:"Cybersecurity",domain:"crowdstrike.com",irUrl:"https://ir.crowdstrike.com",earningsDate:"2026-03-04",earningsTime:"AMC",lastChecked:null,notes:"",sourceUrl:null,sourceLabel:null,earningSummary:null,description:"CrowdStrike provides cloud-delivered endpoint and workload protection. Its Falcon platform uses AI to detect and prevent breaches in real time across endpoints, cloud workloads, identity, and data.",ceo:"George Kurtz",employees:8500,country:"US",exchange:"NASDAQ",ipoDate:"2019-06-12",mktCap:85000000000,thesisNote:"Post-outage recovery.\n\n## MOAT\nFalcon platform has deep endpoint integration — rip-and-replace is painful. Threat intelligence network effect: more endpoints = better detection.\n\n## RISKS\nBrand damage from July 2024 outage may linger. Competitive pressure from SentinelOne, Palo Alto. Government contracts at risk.\n\n## SELL CRITERIA\nGross retention dropping below 95%. Net new ARR below $200M for 2+ quarters. Another major incident.",investStyle:"growth",position:{shares:0,avgCost:0},conviction:6,convictionHistory:[{date:"2025-09-01",rating:5,note:"Outage fallout"},{date:"2026-01-10",rating:6,note:"Recovery underway"}],status:"watchlist",docs:[],earningsHistory:[],kpis:[{id:1,name:"Net New ARR",target:"≥220M",rule:"gte",value:220,unit:"M",period:"Q4 FY26",notes:"",lastResult:null},{id:2,name:"Gross Retention",target:"≥95%",rule:"gte",value:95,unit:"%",period:"Q4 FY26",notes:"",lastResult:null}]}];

export {
  METRICS,
  METRIC_MAP,
  INVEST_STYLES,
  STYLE_MAP,
  INVESTOR_PROFILES,
  PROFILE_MAP,
  SUPERINVESTORS,
  MSTAR_RATINGS,
  KNOWN_MONTHLY,
  DARK,
  LIGHT,
  FOREST,
  PURPLE,
  BLOOMBERG,
  PAYPAL,
  THESIS_DARK,
  THESIS_LIGHT,
  THEMES,
  FOLDERS,
  SAMPLE,
  ALERT_QUOTES,
  MENTAL_MODELS,
  GLOSSARY,
};
var ALERT_QUOTES=[
  "Now sit on your ass and wait.",
  "Munger would be proud. Now go touch grass.",
  "Alert set. The market will come to you.",
  "Good things come to those who wait. Buffett has been waiting since 1965.",
  "Lynch says: know what you own. You set the price. Now know when to act.",
  "The stock doesn't know you're watching it. But you'll know when it's time.",
  "Patience is the most underrated edge in investing. You just used it.",
  "Temperament beats IQ. Alert set. Now close the app.",
  "Munger: 'I have nothing to add.' Neither do you — until the price hits.",
  "The market is a device for transferring money from the impatient to the patient.",
  "You've done the thinking. Now let the market do the rest.",
  "Alert set. Go read a book. Munger read 500 pages a week.",
  "Waiting is not doing nothing. It's the strategy.",
  "Charlie would call this 'sitting quietly in a room'. Alert set.",
  "You don't get paid for activity. Alert set. Inactivity mode: ON.",
  "The big money is not in the buying or the selling — it's in the waiting.",
  "Price alert set. Your only job now is to not do anything stupid.",
  "Buffett watches paint dry too. Alert set.",
  "You've set your price. The market will come around. It always does.",
  "Fisher said patience is more than a virtue — it's a prerequisite. Alert set.",
];


// ── Learning Hub: Mental Models ──────────────────────────────────────────────
var MENTAL_MODELS=[
  // ── Thinking Frameworks ──────────────────────────────────────────────────
  {id:"inversion",cat:"Thinking",title:"Inversion",author:"Charlie Munger",source:"Poor Charlie's Almanack, 2005",
   tagline:"Invert, always invert.",
   body:"Munger borrowed inversion from the mathematician Carl Jacobi. Rather than asking 'how do I make this investment succeed?', inversion demands you ask 'what would guarantee failure, and how do I avoid it?' Applied to investing: instead of looking for reasons to buy, look hard for reasons you could be wrong. The companies that survive inversion scrutiny — where you genuinely cannot construct a credible bear case — are the most durable investments. Inversion is the engine behind Buffett's two rules: Rule No. 1, never lose money; Rule No. 2, never forget Rule No. 1.",
   quote:"It is remarkable how much long-term advantage people like us have gotten by trying to be consistently not stupid, rather than trying to be very intelligent.",
   quoteSource:"Charlie Munger, USC Law School Commencement, 2007"},

  {id:"circle_of_competence",cat:"Thinking",title:"Circle of Competence",author:"Warren Buffett & Charlie Munger",source:"Berkshire Hathaway Annual Letter, 1996",
   tagline:"Know what you know. Know what you don't.",
   body:"Buffett and Munger define a circle of competence as the domain within which you have genuine, tested understanding — not superficial familiarity. The critical insight is not that your circle must be large; it must have clearly defined edges. Buffett has explicitly stated he cannot value most technology companies with confidence, and he doesn't try. The danger is not ignorance, which is identifiable and manageable. The danger is the illusion of competence — believing you understand a business when you do not. Regularly testing your circle means asking: can I explain this business model, its competitive dynamics, and its long-term economics to an intelligent non-specialist?",
   quote:"What counts for most people in investing is not how much they know, but rather how realistically they define what they don't know.",
   quoteSource:"Warren Buffett, Berkshire Hathaway Annual Letter, 1993"},

  {id:"margin_of_safety",cat:"Valuation",title:"Margin of Safety",author:"Benjamin Graham",source:"The Intelligent Investor, 1949",
   tagline:"The three most important words in investing.",
   body:"Graham defined margin of safety as the gap between a security's intrinsic value and its market price. Buying at a substantial discount to intrinsic value provides protection against analytical errors, unforeseen deterioration in the business, and adverse market events. The concept is deliberately conservative: Graham did not assume his valuations were correct. He assumed they could be wrong by a significant margin, and still required the price to be sufficiently below value to absorb that error. Buffett has called it 'the three most important words in investing.' For high-quality businesses, Buffett later modified Graham's strict quantitative approach, accepting a smaller margin of safety in exchange for superior business economics.",
   quote:"The margin of safety is always dependent on the price paid. It will be large at one price, small at some higher price, nonexistent at some still higher price.",
   quoteSource:"Benjamin Graham, The Intelligent Investor, Chapter 20, 1949"},

  {id:"moat",cat:"Business Quality",title:"Economic Moat",author:"Warren Buffett",source:"Berkshire Hathaway Annual Letter, 1986",
   tagline:"A durable competitive advantage that protects returns on capital.",
   body:"Buffett introduced the moat metaphor to describe the structural barriers that protect a business's returns on invested capital from competitive erosion. A business without a moat will, over time, see its profits competed away. The five primary moat sources identified by Morningstar (building on Buffett's framework) are: intangible assets (brands, patents, regulatory licenses), cost advantages, switching costs, network effects, and efficient scale. The critical distinction is between moats that are durable — able to withstand technological disruption and new entrants for decades — and those that are merely temporary competitive advantages. Munger emphasizes that moat analysis must be dynamic: 'All moats are in constant peril of being drained.'",
   quote:"The key to investing is not assessing how much an industry is going to affect society, or how much it will grow, but rather determining the competitive advantage of any given company.",
   quoteSource:"Warren Buffett, Fortune, 1999"},

  {id:"owner_earnings",cat:"Valuation",title:"Owner Earnings",author:"Warren Buffett",source:"Berkshire Hathaway Annual Letter, 1986",
   tagline:"The cash a business actually generates for its owners.",
   body:"Buffett's owner earnings formula: reported earnings + depreciation/depletion/amortisation − average annual maintenance capital expenditure. The key departure from GAAP earnings is the treatment of capital expenditure. GAAP separates capex from the income statement, but Buffett argues that maintenance capex — the spending required merely to sustain a business's competitive position and unit volume — is an economic cost as real as wages. Businesses with large reinvestment requirements (airlines, steel mills) generate far less owner earnings than their reported earnings imply. Asset-light businesses with low maintenance capex (insurance, software) generate owner earnings that typically exceed reported earnings. Buffett uses owner earnings as the denominator in his effective P/E calculation.",
   quote:"'Reported earnings' — defined as reported profits plus D&D minus capex — is the most important figure for owners trying to evaluate the economic value of a business.",
   quoteSource:"Warren Buffett, Berkshire Hathaway Annual Letter, 1986"},

  {id:"roic",cat:"Business Quality",title:"Return on Invested Capital",author:"Joel Greenblatt",source:"The Little Book That Beats the Market, 2005",
   tagline:"The most important metric in equity analysis.",
   body:"ROIC measures the after-tax operating profit generated per dollar of capital deployed in the business. It is calculated as NOPAT (Net Operating Profit After Tax) divided by invested capital (equity + net debt). A business that consistently earns ROIC above its cost of capital is creating shareholder value; one that earns below destroys it. The durability of high ROIC — not the level in any single year — is the signal of a genuine moat. Greenblatt's 'Magic Formula' uses ROIC as its quality screen precisely because high-ROIC businesses tend to mean-revert less than markets expect. Munger and Buffett focus on the long-run ROIC trajectory as the acid test of whether a moat is real or temporary.",
   quote:"The secret to investing is to figure out the value of something — and then pay a lot less.",
   quoteSource:"Joel Greenblatt, The Little Book That Beats the Market, 2005"},

  {id:"compounding",cat:"Thinking",title:"Compound Interest",author:"Albert Einstein (attributed)",source:"Poor Charlie's Almanack; Berkshire Letters",
   tagline:"The eighth wonder of the world.",
   body:"Compounding is the process by which investment returns generate further returns over time. Its power is non-linear: at 15% annual returns, money doubles in approximately 4.8 years; at 20%, in 3.6 years. The critical variables are rate of return and time. Buffett's singular insight was that owning wonderful businesses — those with high returns on capital that can reinvest earnings at similarly high rates — creates a self-reinforcing compounding engine. His core holding periods ('our favourite holding period is forever') reflect the mathematics: each year of continued compounding at high rates matters enormously. Conversely, transaction friction (taxes, commissions, bid-ask spreads) has a compounding drag effect that most investors systematically underestimate.",
   quote:"Understanding both the power of compound interest and the difficulty of getting it is the heart and soul of understanding a lot of things.",
   quoteSource:"Charlie Munger, USC Business School, 1994"},

  {id:"opportunity_cost",cat:"Thinking",title:"Opportunity Cost",author:"Charlie Munger",source:"Poor Charlie's Almanack, 2005",
   tagline:"Every investment decision is a comparison.",
   body:"Opportunity cost is the return foregone by choosing one investment over the best available alternative. Munger argues that most investors evaluate investments in isolation — asking only 'is this good?' — when the correct question is 'is this better than everything else I could do with this capital?' The practical implication: Berkshire's hurdle rate is not a fixed percentage but the expected return from their next-best alternative. Buffett has said that if you own the best business in the world, you should only sell it if you identify something better. This framing dramatically raises the bar for both purchases and sales, and explains why both Buffett and Munger hold concentrated portfolios — they only act when they find something clearly superior.",
   quote:"Intelligent people make decisions based on opportunity costs — in other words, it's your alternatives that matter. That's how we make all of our decisions.",
   quoteSource:"Charlie Munger, Berkshire Annual Meeting, 2003"},

  {id:"lollapalooza",cat:"Thinking",title:"Lollapalooza Effect",author:"Charlie Munger",source:"The Psychology of Human Misjudgment, 1995",
   tagline:"Multiple cognitive biases acting in the same direction simultaneously.",
   body:"Munger coined 'lollapalooza' to describe situations where several psychological tendencies reinforce each other, producing extreme outcomes that no single tendency could explain. In investing, lollapalooza effects drive bubbles (social proof + incentive bias + availability heuristic + FOMO all pointing in the same direction) and catastrophic capital allocation (overconfidence + commitment bias + social proof from industry peers). The antidote is systematic checklisting — ensuring you identify which biases are potentially active in any decision, especially when multiple biases point the same way. Munger's 25 cognitive biases, compiled in 'The Psychology of Human Misjudgment', are the most comprehensive applied psychology framework in investment literature.",
   quote:"If you get a lot of confluences, you often get lollapalooza effects — which can be for good or ill.",
   quoteSource:"Charlie Munger, Harvard Law School, 1995"},

  {id:"fat_pitch",cat:"Process",title:"Fat Pitch",author:"Warren Buffett",source:"Berkshire Hathaway Annual Letter, 1997",
   tagline:"Swing hard, but only at the right pitch.",
   body:"Buffett borrowed the fat pitch metaphor from baseball legend Ted Williams, who described how he divided the strike zone into 77 cells and only swung at pitches in his highest-percentage cells. In investing, a fat pitch is a situation where the odds are dramatically in your favour: a high-quality business, well understood, temporarily available at a price that implies an exceptional return. The critical difference from baseball: in investing, you can wait indefinitely without penalty for the fat pitch. There is no called strike for not swinging. This explains Buffett's willingness to hold large cash positions for years — he is not waiting to deploy capital; he is waiting for the pitch that meets his full criteria. Most investors swing at too many borderline pitches.",
   quote:"We try to exert a Ted Williams kind of discipline. In his book 'The Science of Hitting', Ted explains that he carved the strike zone into 77 cells... Swinging only at pitches in your 'best' cells is the way to a .400 batting average.",
   quoteSource:"Warren Buffett, Berkshire Hathaway Annual Letter, 1997"},

  {id:"price_value",cat:"Valuation",title:"Price vs. Value",author:"Benjamin Graham",source:"Security Analysis, 1934",
   tagline:"Price is what you pay. Value is what you get.",
   body:"Graham's foundational distinction separates market price — a function of sentiment, liquidity, and short-term information — from intrinsic value, which derives from the present value of all future cash flows the business will generate. In the short run, Mr. Market (Graham's allegorical market participant) sets prices based on mood, from euphoric to despairing. In the long run, price converges on value. The practical implication: the stock market is a voting machine in the short term and a weighing machine in the long term. Buffett has repeatedly credited this distinction — and its corollary, that volatility is not risk but opportunity for the disciplined investor — as the most important insight he absorbed from Graham's teaching.",
   quote:"In the short run, the market is a voting machine but in the long run, it is a weighing machine.",
   quoteSource:"Benjamin Graham, Security Analysis, 1934"},

  {id:"management_quality",cat:"Business Quality",title:"Management Quality",author:"Philip Fisher",source:"Common Stocks and Uncommon Profits, 1958",
   tagline:"Invest in people, not just businesses.",
   body:"Fisher's scuttlebutt method — gathering information from suppliers, customers, competitors, and former employees — was designed primarily to assess management quality. His key dimensions: integrity (do they act in shareholders' interests?), competence (do they allocate capital intelligently?), and adaptability (do they reinvest in the business's long-run competitive position, even at short-term profit cost?). Fisher famously warned that businesses with excellent economics but poor management will eventually be damaged, while businesses with average economics but exceptional management can be dramatically improved. Munger's addition: look for managers who think like owners — who bought their stock with their own money and did not receive most of it through options.",
   quote:"The management of the companies in which you invest will determine, to a very large extent, the quality of the results you achieve.",
   quoteSource:"Philip Fisher, Common Stocks and Uncommon Profits, 1958"},

  {id:"mean_reversion",cat:"Thinking",title:"Mean Reversion",author:"Benjamin Graham",source:"Security Analysis; Howard Marks",
   tagline:"Abnormal returns attract competition until they become normal.",
   body:"Mean reversion is the empirical tendency for extreme values — unusually high profit margins, unusually high returns on capital, unusually high valuations — to revert toward historical averages over time. In competitive markets, high returns on capital attract new entrants and incremental investment by incumbents until returns converge toward the cost of capital. Understanding mean reversion is essential to long-run valuation: a business currently earning 40% gross margins should not be valued assuming 40% gross margins indefinitely unless there is a clear structural reason (a genuine moat) why competition cannot erode them. The practical error is extrapolating peak conditions — the source of most valuation disasters at market tops.",
   quote:"Everything reverts to the mean in the long run.",
   quoteSource:"Howard Marks, The Most Important Thing, 2011"},

  {id:"incentives",cat:"Thinking",title:"Incentive-Caused Bias",author:"Charlie Munger",source:"The Psychology of Human Misjudgment, 1995",
   tagline:"Show me the incentive and I'll show you the outcome.",
   body:"Munger's most frequently cited mental model: people's behaviour is powerfully shaped by incentive structures, often in ways they themselves do not consciously recognise. Applied to investing: always ask how management is compensated, and whether those incentives align with long-term shareholder value. Stock options create incentives to inflate short-term earnings. Empire-building incentives lead to value-destroying acquisitions. Fee structures in fund management create incentives for asset gathering rather than return generation. The antidote is to follow the incentives before forming a view — not to assume rational, shareholder-aligned behaviour as a baseline.",
   quote:"Never, ever, think about something else when you should be thinking about the power of incentives.",
   quoteSource:"Charlie Munger, Poor Charlie's Almanack, 2005"},

  {id:"network_effects",cat:"Business Quality",title:"Network Effects",author:"Metcalfe's Law (applied to investing)",source:"Peter Thiel, Zero to One, 2014",
   tagline:"The value of a network grows with the square of its users.",
   body:"A business with network effects becomes more valuable to each user as the total number of users grows — creating a self-reinforcing moat. Metcalfe's Law states that network value scales with n² (where n = users), meaning network effects compound dramatically at scale. The practical implication: network-effect businesses tend to be winner-take-most or winner-take-all in their categories, creating extreme barriers to displacement. Visa, Mastercard, MSCI's index data, LSEG's clearing infrastructure, and Apple's App Store all exhibit network effects. The investor's task is to distinguish genuine network effects (where each additional user adds value to all existing users) from mere scale advantages (where costs decline with volume but user-to-user value is absent).",
   quote:"Network effects are the most powerful form of competitive advantage, and the most durable.",
   quoteSource:"Peter Thiel, Zero to One, 2014"},

  {id:"switching_costs",cat:"Business Quality",title:"Switching Costs",author:"Michael Porter",source:"Competitive Advantage, 1985",
   tagline:"The cost — financial, operational, or psychological — of leaving.",
   body:"Switching costs are barriers that make it costly or disruptive for customers to change suppliers, even when alternatives exist. They manifest as: contractual lock-in (multi-year enterprise software contracts), data portability barriers (ERP systems that accumulate years of a company's data), workflow integration (software deeply embedded in operational processes), training costs (staff proficiency in existing tools), and psychological inertia (the known vs. the unknown). High switching costs allow businesses to raise prices gradually without losing customers, generating pricing power that compounds over time. Tyler Technologies, Constellation Software, and Veeva Systems are canonical examples. The investor must assess whether switching costs are durable — i.e., whether technological change could suddenly make switching easy.",
   quote:"Switching costs arise from the buyer's investment in learning, equipment, data, and supplier relationships.",
   quoteSource:"Michael Porter, Competitive Advantage, 1985"},

  {id:"scuttlebutt",cat:"Process",title:"Scuttlebutt Method",author:"Philip Fisher",source:"Common Stocks and Uncommon Profits, 1958",
   tagline:"Go beyond the financial statements.",
   body:"Fisher's scuttlebutt method involves systematically gathering qualitative information from people who interact with a company — customers, suppliers, former employees, competitors, and industry analysts — to build a picture of the business that cannot be obtained from financial statements alone. The goal is to understand: Is the business regarded as an excellent employer? Do competitors respect it? Does it have exceptional depth in management? Is it focused on long-term earnings growth rather than short-term reporting? Fisher argued that most investors rely almost exclusively on published financial data and management communications — sources that are curated and potentially misleading. The scuttlebutt approach produces genuinely differentiated insight, which is the prerequisite for an informational edge.",
   quote:"The really great investments come from doing your homework far more thoroughly than the average investor.",
   quoteSource:"Philip Fisher, Common Stocks and Uncommon Profits, Chapter 3, 1958"},

  {id:"patience",cat:"Process",title:"Patience as Process",author:"Warren Buffett",source:"Berkshire Hathaway Annual Letters",
   tagline:"The ability to sit on your hands is a competitive advantage.",
   body:"Buffett has repeatedly described the temperament required for long-term investment success as more important than analytical ability. Most investors' biggest errors are not analytical failures but behavioural ones: selling high-quality businesses too early because of short-term noise, reacting to market volatility as though it represented a change in intrinsic value, or buying marginal businesses because capital feels idle. Buffett's framework: hold a business as long as it remains excellent, its competitive position is intact, and you have no better alternative use for the capital. The holding-period question is not 'when should I sell?' but 'what has fundamentally changed that would alter my original thesis?' Patience is the mechanism by which compounding works.",
   quote:"The stock market is a device for transferring money from the impatient to the patient.",
   quoteSource:"Warren Buffett, Berkshire Hathaway Annual Letter, 1985"},
];

// ── Learning Hub: Concept Glossary ─────────────────────────────────────────
var GLOSSARY=[
  {id:"roic",term:"Return on Invested Capital (ROIC)",cat:"Metrics",
   definition:"NOPAT ÷ Invested Capital. Measures after-tax operating profitability relative to the total capital deployed (equity + net debt). The most important single metric for assessing whether a business is creating or destroying value. Businesses earning ROIC consistently above their weighted average cost of capital (WACC) create economic value; those earning below destroy it.",
   formula:"ROIC = NOPAT / (Total Equity + Total Debt − Cash)",
   threshold:"≥15% is generally considered excellent. ≥25% indicates a strong moat. Below 8% suggests structural disadvantage.",
   source:"Joel Greenblatt, The Little Book That Beats the Market, 2005"},

  {id:"gross_margin",term:"Gross Margin",cat:"Metrics",
   definition:"(Revenue − Cost of Goods Sold) ÷ Revenue. Measures the percentage of revenue retained after direct production costs. High gross margins are a primary indicator of pricing power — the ability to charge more than it costs to produce. Software businesses often achieve 70–80% gross margins; commodity businesses may struggle to exceed 20%. Gross margin stability over time is as important as its absolute level.",
   formula:"Gross Margin = (Revenue − COGS) / Revenue × 100",
   threshold:"SaaS: 70–80% typical. Consumer brands: 40–60%. Industrial/manufacturing: 20–40%. Below 20% suggests commodity dynamics.",
   source:"Aswath Damodaran, Investment Valuation, 2012"},

  {id:"fcf",term:"Free Cash Flow (FCF)",cat:"Metrics",
   definition:"Operating Cash Flow minus Capital Expenditure. The cash a business generates after maintaining and investing in its physical asset base. FCF is the foundation of all valuation frameworks because it represents actual cash available for distribution to shareholders, debt reduction, acquisitions, or reinvestment. Divergence between earnings and FCF over extended periods is a significant red flag.",
   formula:"FCF = Operating Cash Flow − Capital Expenditure",
   threshold:"FCF yield (FCF/Market Cap) above 5% is generally considered attractive for quality businesses. FCF conversion (FCF/Net Income) above 100% is excellent.",
   source:"Warren Buffett, Berkshire Hathaway Annual Letter, 1986"},

  {id:"owner_earnings_g",term:"Owner Earnings",cat:"Metrics",
   definition:"Buffett's preferred measure of a business's economic output. Reported net income + Depreciation/Amortisation − Maintenance Capital Expenditure − Required Working Capital increases. Unlike FCF, owner earnings uses estimated maintenance capex rather than total capex, separating the capital required to sustain the business from the capital deployed to grow it.",
   formula:"Owner Earnings = Net Income + D&A − Maintenance Capex ± Working Capital Changes",
   threshold:"Owner earnings significantly above reported net income typically indicates asset-light business model. Significantly below suggests heavy reinvestment requirement.",
   source:"Warren Buffett, Berkshire Hathaway Annual Letter, 1986"},


  {id:"moat_g",term:"Economic Moat",cat:"Concepts",
   definition:"A structural competitive advantage that enables a business to earn returns on invested capital above its cost of capital for an extended period, despite competitive pressure. Morningstar categorises moat sources as: intangible assets (brands, patents, regulatory licences), cost advantages, switching costs, network effects, and efficient scale. Wide moat businesses are expected to maintain competitive advantage for 20+ years; narrow moat for 10+ years.",
   formula:null,
   threshold:"Wide moat: ROIC sustainably above WACC for 20+ years. Narrow moat: 10–20 years. No moat: returns likely to converge to cost of capital within 10 years.",
   source:"Pat Dorsey, The Little Book That Builds Wealth, 2008"},

  {id:"wacc",term:"Weighted Average Cost of Capital (WACC)",cat:"Valuation",
   definition:"The minimum return a business must generate to satisfy all capital providers — equity holders and debt holders. WACC represents the opportunity cost of the capital invested in the business. A business earning ROIC above its WACC creates value; below destroys it. The gap between ROIC and WACC, multiplied by invested capital, defines economic profit (EVA).",
   formula:"WACC = (E/V × Re) + (D/V × Rd × (1−T)) where E=equity, D=debt, V=total capital, Re=cost of equity, Rd=cost of debt, T=tax rate",
   threshold:"Typical WACC ranges: 8–12% for large-cap developed markets; 10–15% for emerging markets; 6–10% for utilities and regulated businesses.",
   source:"Aswath Damodaran, Applied Corporate Finance, 2014"},

  {id:"dcf",term:"Discounted Cash Flow (DCF)",cat:"Valuation",
   definition:"A valuation methodology that estimates intrinsic value as the present value of all future free cash flows, discounted at the cost of capital. DCF is theoretically complete — it captures all the variables that determine value — but is highly sensitive to assumptions about growth rates, terminal value, and discount rates. Small changes in these assumptions produce large changes in valuation output. Buffett uses DCF conceptually but rarely mechanically, preferring to ask whether free cash flows at a conservative discount rate justify the current price.",
   formula:"Intrinsic Value = Σ(FCFt / (1+r)^t) + Terminal Value / (1+r)^n",
   threshold:"A 1% change in the discount rate can move intrinsic value by 15–25%. Terminal value typically represents 60–80% of total DCF value, making growth rate assumptions critical.",
   source:"Benjamin Graham & David Dodd, Security Analysis, 1934"},

  {id:"pe_ratio",term:"Price-to-Earnings Ratio (P/E)",cat:"Valuation",
   definition:"Market price per share divided by earnings per share. The most widely used valuation multiple, representing the number of years of current earnings required to justify the current price. P/E is a reciprocal of earnings yield: a P/E of 20x implies a 5% earnings yield. P/E must always be contextualised by earnings quality, growth rate, and the interest rate environment — a 20x P/E for a business growing earnings at 20% per year (PEG of 1.0) is materially different from a 20x P/E for a business with flat earnings.",
   formula:"P/E = Market Price per Share / Earnings per Share",
   threshold:"Historical S&P 500 average: ~16x. Below 15x: potentially cheap. 15–25x: fair value range for quality. Above 35x: growth expectations are very demanding.",
   source:"Benjamin Graham, The Intelligent Investor, 1949"},

  {id:"circle_g",term:"Circle of Competence",cat:"Concepts",
   definition:"The domain within which an investor has genuine, tested understanding of a business's economics, competitive dynamics, and long-run prospects. Developed by Buffett and Munger to address the consistent error of investors acting outside their knowledge boundaries. The circle is defined not by the investor's confidence level but by their demonstrated ability to make accurate predictions about the business over multiple cycles.",
   formula:null,
   threshold:"Munger's test: can you identify five legitimate reasons the business might fail? If not, your circle may not yet encompass it.",
   source:"Warren Buffett, Berkshire Hathaway Annual Letter, 1996"},

  {id:"margin_safety_g",term:"Margin of Safety",cat:"Concepts",
   definition:"The discount between the market price of a security and its estimated intrinsic value. Graham required this gap to provide protection against valuation errors and unforeseen deterioration. The larger the uncertainty in the valuation, the larger the required margin of safety. For businesses with highly predictable earnings and strong competitive positions, a 15–20% discount may suffice. For cyclical, capital-intensive, or rapidly changing businesses, Graham recommended discounts of 50% or more.",
   formula:"Margin of Safety = (Intrinsic Value − Market Price) / Intrinsic Value × 100",
   threshold:"Graham's baseline: 33% minimum (buy at ≤2/3 of intrinsic value). For high-quality businesses: 15–25% is commonly accepted. For deep-value situations: 40–50%.",
   source:"Benjamin Graham, The Intelligent Investor, Chapter 20, 1949"},
];

// ── Additional Glossary Entries ───────────────────────────────────────────
var GLOSSARY_EXTRA=[
  {id:"ev_ebitda",term:"EV/EBITDA",cat:"Valuation",
   definition:"Enterprise Value divided by Earnings Before Interest, Taxes, Depreciation, and Amortisation. A capital-structure-neutral valuation multiple — unlike P/E, it is unaffected by leverage or tax treatment, making it the preferred multiple for comparing companies across capital structures and geographies. EV = market cap + net debt + minority interests. EBITDA approximates operating cash generation before capital allocation decisions.",
   formula:"EV/EBITDA = (Market Cap + Net Debt) / EBITDA",
   threshold:"Below 10x: potentially cheap for a quality business. 10–20x: fair value range. Above 25x: pricing in significant growth. Below 7x may indicate a value trap — always check why.",
   source:"Aswath Damodaran, Investment Valuation, 2012"},

  {id:"free_cash_flow",term:"Free Cash Flow (FCF)",cat:"Metrics",
   definition:"Operating cash flow minus capital expenditure. The cash a business generates after maintaining its asset base — the most honest measure of economic output because it cannot be manipulated through accrual accounting. A business that consistently earns net income but generates no FCF is likely consuming cash through working capital growth or excessive capex. Persistent FCF > net income signals a high-quality, asset-light model.",
   formula:"FCF = Operating Cash Flow − Capital Expenditure",
   threshold:"FCF yield (FCF/Market Cap) above 4–5% is generally attractive. FCF conversion (FCF/Net Income) above 90% is excellent; below 60% warrants investigation.",
   source:"Warren Buffett, Berkshire Hathaway Annual Letter, 1986"},

  {id:"capital_allocation",term:"Capital Allocation",cat:"Concepts",
   definition:"The decisions a management team makes about where to deploy the cash a business generates: reinvestment in organic growth, acquisitions, debt repayment, dividends, or buybacks. Buffett has argued that capital allocation is the CEO's most important function — and the one for which they receive the least training. The test: does each dollar retained create more than one dollar of market value? A business that compounds at 20% ROIC but allocates capital into low-return acquisitions destroys far more value than the core operations create.",
   formula:"Return on Incremental Capital = Change in NOPAT / Capital Invested",
   threshold:"Management that has compounded book value per share above 15% per year for a decade has demonstrated capital allocation skill. Watch for serial acquirers whose goodwill grows faster than earnings.",
   source:"Warren Buffett, Berkshire Hathaway Annual Letter, 1987"},

  {id:"buybacks",term:"Share Buybacks",cat:"Concepts",
   definition:"A company repurchasing its own shares, reducing the share count and increasing per-share metrics (EPS, FCF per share, book value per share) for remaining shareholders. Buybacks are value-creating only when the shares are repurchased below intrinsic value. Buybacks at inflated prices — particularly common when management is compensated in options — are a capital allocation failure. Munger: 'All buybacks are not created equal. The ones done at 30x earnings when the business is deteriorating are destructive.'",
   formula:"Buyback Yield = (Shares Repurchased × Price) / Market Cap",
   threshold:"Net buyback yield (buybacks minus issuance) above 3% at prices below intrinsic value is shareholder-friendly. Watch for companies that issue options to management and buy back shares to neutralise dilution — this transfers value from shareholders to management.",
   source:"Michael Mauboussin, Expectations Investing, 2001"},

  {id:"net_debt_ebitda",term:"Net Debt/EBITDA",cat:"Metrics",
   definition:"Total financial debt minus cash and equivalents, divided by EBITDA. Measures how many years of operating earnings would be required to repay net debt. The primary leverage ratio used by credit analysts and lenders. A business with Net Debt/EBITDA above 4x has limited financial flexibility and is vulnerable in downturns. Net Cash (negative net debt) provides optionality and is a competitive advantage in crises.",
   formula:"Net Debt/EBITDA = (Total Debt − Cash) / EBITDA",
   threshold:"0–1x: conservative. 1–2x: modest. 2–3x: elevated. Above 4x: high risk. Net cash position: exceptional flexibility.",
   source:"Standard & Poor's Credit Ratings Methodology"},

  {id:"scuttlebutt_g",term:"Scuttlebutt",cat:"Process",
   definition:"Philip Fisher's term for the practice of gathering qualitative competitive intelligence from a business's ecosystem — customers, suppliers, competitors, former employees, and industry analysts. The goal is to develop an understanding of the business that cannot be obtained from financial statements or management presentations alone. Fisher argued that publicly available information is already in the price; the edge comes from better-than-average qualitative insight about management quality, competitive dynamics, and reinvestment discipline.",
   formula:null,
   threshold:"Fisher's 15 questions (Common Stocks and Uncommon Profits, 1958) provide the framework: Does the company have products with sufficient market potential? How effective is the R&D? Does management communicate honestly with investors when things go wrong?",
   source:"Philip Fisher, Common Stocks and Uncommon Profits, Chapter 3, 1958"},
];
GLOSSARY=GLOSSARY.concat(GLOSSARY_EXTRA);
